require 'swift/monkey/datamapper'
require 'swift/monkey/http_router'
require 'swift/monkey/i18n'
require 'swift/monkey/markdown'
require 'swift/monkey/padrino'
require 'swift/monkey/rack'
require 'swift/monkey/sinatra'
