#coding:utf-8

Folder.all.destroy!
Page.all.destroy!
Account.all.destroy!

k = 1
ACCOUNT_GROUPS.each do |g|
  pwd = SecureRandom.hex(4)
  a = Account.create :id => k, :email => "#{g}@localhost", :name => g, :surname => 'group', :password => pwd, :password_confirmation => pwd, :group => nil
  k += 1
end
account = Account.first

# pages

root  = Page.create :parent => nil,   :slug => '',        :title => 'Index', :text => 'index'
error = Page.create :parent => root,  :slug => 'error',   :title => 'Error', :text => 'Default error page', :is_published => false
admin = Page.create :parent => root,  :slug => 'admin',   :title => 'Admin panel'
about = Page.create :parent => root,  :slug => 'about',   :title => 'About this site', :text => 'This web site is generated by Swift Singer'
Page.create :parent => root,  :slug => 'about1',   :title => 'About this site 1', :text => '1 This web site is generated by Swift Singer'
Page.create :parent => root,  :slug => 'about2',   :title => 'About this site 2', :text => '2 This web site is generated by Swift Singer'
Page.create :parent => root,  :slug => 'about3',   :title => 'About this site 3', :text => '3 This web site is generated by Swift Singer'
Page.create :parent => root,  :slug => 'about4',   :title => 'About this site 4', :text => '4 This web site is generated by Swift Singer'

Page.create         :parent => error, :slug => '404',     :title => '404 Not Found',   :text => 'Sorry, page not found', :is_published => false
Page.create         :parent => error, :slug => '501',     :title => '501 Service Unavailable',   :text => 'Sorry, requested service is unavailable', :is_published => false

p1= Page.create         :parent => about, :slug => 'phones',  :title => 'Phones',  :text => '12341234'
p2= Page.create         :parent => about, :slug => 'address', :title => 'Address', :text => 'alemrawec ruawercw'
p3= Page.create         :parent => about, :slug => 'map',     :title => 'map',     :text => 'THERE'

Page.create         :parent => p1, :slug => 'map1',     :title => 'map1',     :text => 'THERE 1'
Page.create         :parent => p2, :slug => 'map2',     :title => 'map2',     :text => 'THERE 2'
Page.create         :parent => p3, :slug => 'map3',     :title => 'map3',     :text => 'THERE 3'
Page.create         :parent => p1, :slug => 'map4',     :title => 'map4',     :text => 'THERE 4'

# folders
Folder.create :id => 1, :account => nil, :title => 'Layout graphics', :slug => 'images'
Folder.create :id => 2, :account => nil, :title => 'Common files', :slug => 'files'

# layouts
Layout.create :slug => 'application', :title => 'Default app'
Layout.create :slug => 'raw',         :title => 'Raw data'

# fragments
Fragment.create :title => 'Footer',       :slug => 'footer', :is_basic => false
Fragment.create :title => 'Header',       :slug => 'header', :is_basic => false
Fragment.create :title => 'Default page', :slug => 'page',   :is_basic => true
